In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [3]:
df = pd.read_csv('Churn_Modelling.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
df = df.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [5]:
label_encoder_gender = LabelEncoder()
df['Gender'] = label_encoder_gender.fit_transform(df['Gender'])

In [ ]:
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(df[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [7]:
df = pd.concat([df.drop('Geography',axis=1),geo_encoded_df],axis=1)
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [8]:
X = df.drop('EstimatedSalary',axis=1)
y = df['EstimatedSalary']

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

#### train ANN with the regression problem statement

In [12]:
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
model = Sequential ([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1,activation='linear')
])

c:\Users\VEDANT\anaconda3\envs\tf_env\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [14]:
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])
model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

logs_dir = "regression_logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=logs_dir,histogram_freq=1)

In [16]:
## Erly stopping
early_stopping = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [17]:
history = model.fit(
    X_train,y_train,
    validation_data=(X_test,y_test),
    epochs=100,
    callbacks=[early_stopping,tensorboard_callback])

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 100392.8594 - mae: 100392.8594 - val_loss: 98574.3438 - val_mae: 98574.3438
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 99819.8984 - mae: 99819.8984 - val_loss: 97400.8672 - val_mae: 97400.8672
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 97736.0781 - mae: 97736.0781 - val_loss: 94321.6094 - val_mae: 94321.6094
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 93532.2188 - mae: 93532.2188 - val_loss: 89035.3594 - val_mae: 89035.3594
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 87190.2812 - mae: 87190.2812 - val_loss: 81885.4375 - val_mae: 81885.4375
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 79351.1094 - mae: 79351.1094 - val_loss: 73909.5859 - val_mae: 73909.5859
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 71101.0078 - mae: 71101.0078 - val_loss: 66171.1250 - val_mae: 66171.1250
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 63603.8086 - mae: 63603.8086 - val_loss: 59755.5781 - val_mae: 59755.5781
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 57781.8984 - mae: 57781.8984 - val_loss: 55227.3672 - val_mae: 55227.3672
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 53990.3203 - mae: 53990.3203 - val_loss: 52590.7305 - val_mae: 52590.7305
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 51887.9453 - mae: 51887.9453 - val_loss: 51341.2031 - val_mae: 51341.2031
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 50912.8398 - mae: 50912.8398 - val_loss: 50925.6328 - val_mae: 50925.6328
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 50521.1602 - mae: 50521.1602 - val_loss: 50767.0938 - val_mae: 50767.0938
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 50347.0273 - mae: 50347.0273 - val_loss: 50677.9062 - val_mae: 50677.9062
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 50246.5039 - mae: 50246.5039 - val_loss: 50617.0898 - val_mae: 50617.0898
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50178.8711 - mae: 50178.8711 - val_loss: 50567.1992 - val_mae: 50567.1992
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50122.5469 - mae: 50122.5469 - val_loss: 50532.5547 - val_mae: 50532.5547
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 50077.9570 - mae: 50077.9570 - val_loss: 50502.2930 - val_mae: 50502.2930
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50037.0703 - mae: 50037.0703 - val_loss: 50475.3242 - val_mae: 50475.3242
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49998.9688 - mae: 49998.9688 - val_loss: 50447.8008 - val_mae: 50447.8008
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49968.6328 - mae: 49968.6328 - val_loss: 50425.5703 - val_mae: 50425.5703
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49941.0078 - mae: 49941.0078 - val_loss: 50405.3828 - val_mae: 50405.3828
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49913.3633 - mae: 49913.3633 - val_loss: 50386.8398 - val_mae: 50386.8398
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49888.6016 - mae: 49888.6016 - val_loss: 50370.4453 - val_mae: 50370.4453
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49865.5586 - mae: 49865.5586 - val_loss: 50352.9219 - val_mae: 50352.9219
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49843.8867 - mae: 49843.8867 - val_loss: 50341.0508 - val_mae: 50341.0508
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49821.4258 - mae: 49821.4258 - val_loss: 50324.1523 - val_mae: 50324.1523
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49803.0312 - mae: 49803.0312 - val_loss: 50309.4688 - val_mae: 50309.4688
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49785.5156 - mae: 49785.5156 - val_loss: 50291.4375 - val_mae: 50291.4375
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49768.4023 - mae: 49768.4023 - val_loss: 50278.7734 - val_mae: 50278.7734
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49748.4258 - mae: 49748.4258 - val_loss: 50274.3945 - val_mae: 50274.3945
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49734.5625 - mae: 49734.5625 - val_loss: 50260.6914 - val_mae: 50260.6914
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49718.8164 - mae: 49718.8164 - val_loss: 50253.6289 - val_mae: 50253.6289
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49707.2461 - mae: 49707.2461 - val_loss: 50247.4805 - val_mae: 50247.4805
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49692.1719 - mae: 49692.1719 - val_loss: 50231.1016 - val_mae: 50231.1016
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49682.9961 - mae: 49682.9961 - val_loss: 50228.7266 - val_mae: 50228.7266
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49673.6133 - mae: 49673.6133 - val_loss: 50227.5586 - val_mae: 50227.5586
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49664.6758 - mae: 49664.6758 - val_loss: 50215.6797 - val_mae: 50215.6797
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49650.4375 - mae: 49650.4375 - val_loss: 50218.6289 - val_mae: 50218.6289
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49639.6914 - mae: 49639.6914 - val_loss: 50212.3047 - val_mae: 50212.3047
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 8s 29ms/step - loss: 49631.2539 - mae: 49631.2539 - val_loss: 50208.4883 - val_mae: 50208.4883
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 20ms/step - loss: 49620.7852 - mae: 49620.7852 - val_loss: 50198.6367 - val_mae: 50198.6367
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 49611.2422 - mae: 49611.2422 - val_loss: 50199.6094 - val_mae: 50199.6094
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49602.0664 - mae: 49602.0664 - val_loss: 50197.1562 - val_mae: 50197.1562
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 7s 26ms/step - loss: 49597.0547 - mae: 49597.0547 - val_loss: 50194.3320 - val_mae: 50194.3320
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - loss: 49587.6016 - mae: 49587.6016 - val_loss: 50194.8320 - val_mae: 50194.8320
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 49578.9648 - mae: 49578.9648 - val_loss: 50186.0117 - val_mae: 50186.0117
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49573.1055 - mae: 49573.1055 - val_loss: 50183.2891 - val_mae: 50183.2891
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 23ms/step - loss: 49563.1094 - mae: 49563.1094 - val_loss: 50186.6758 - val_mae: 50186.6758
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49557.5078 - mae: 49557.5078 - val_loss: 50186.1641 - val_mae: 50186.1641
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 22ms/step - loss: 49552.6875 - mae: 49552.6875 - val_loss: 50188.5000 - val_mae: 50188.5000
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49546.7734 - mae: 49546.7734 - val_loss: 50195.8867 - val_mae: 50195.8867
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49538.8047 - mae: 49538.8047 - val_loss: 50184.3750 - val_mae: 50184.3750
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49533.7148 - mae: 49533.7148 - val_loss: 50186.2617 - val_mae: 50186.2617
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49523.3359 - mae: 49523.3359 - val_loss: 50186.3359 - val_mae: 50186.3359
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49517.9531 - mae: 49517.9531 - val_loss: 50179.6016 - val_mae: 50179.6016
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49512.0703 - mae: 49512.0703 - val_loss: 50184.6641 - val_mae: 50184.6641
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49506.7148 - mae: 49506.7148 - val_loss: 50182.3203 - val_mae: 50182.3203
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 49500.9883 - mae: 49500.9883 - val_loss: 50173.1211 - val_mae: 50173.1211
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 23ms/step - loss: 49495.3125 - mae: 49495.3125 - val_loss: 50169.8789 - val_mae: 50169.8789
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 18ms/step - loss: 49489.6289 - mae: 49489.6289 - val_loss: 50190.3555 - val_mae: 50190.3555
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49486.6094 - mae: 49486.6094 - val_loss: 50178.2734 - val_mae: 50178.2734
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49479.2617 - mae: 49479.2617 - val_loss: 50179.3320 - val_mae: 50179.3320
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49474.4531 - mae: 49474.4531 - val_loss: 50164.5742 - val_mae: 50164.5742
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49469.6328 - mae: 49469.6328 - val_loss: 50177.9922 - val_mae: 50177.9922
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49463.8281 - mae: 49463.8281 - val_loss: 50172.3555 - val_mae: 50172.3555
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49457.7930 - mae: 49457.7930 - val_loss: 50175.5312 - val_mae: 50175.5312
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49455.5977 - mae: 49455.5977 - val_loss: 50192.1758 - val_mae: 50192.1758
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49450.1680 - mae: 49450.1680 - val_loss: 50181.2461 - val_mae: 50181.2461
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49442.2109 - mae: 49442.2109 - val_loss: 50178.3906 - val_mae: 50178.3906
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49441.3047 - mae: 49441.3047 - val_loss: 50181.3086 - val_mae: 50181.3086
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49436.0508 - mae: 49436.0508 - val_loss: 50184.5508 - val_mae: 50184.5508
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49432.6211 - mae: 49432.6211 - val_loss: 50184.7656 - val_mae: 50184.7656
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49425.5391 - mae: 49425.5391 - val_loss: 50178.4648 - val_mae: 50178.4648

In [24]:
%load_ext tensorboard
%tensorboard --logdir regression_logs/fit

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
Traceback (most recent call last):
  File "C:\Users\VEDANT\anaconda3\envs\tf_env\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\VEDANT\anaconda3\envs\tf_env\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\VEDANT\anaconda3\envs\tf_env\Scripts\tensorboard.exe\__main__.py", line 2, in <module>
  File "C:\Users\VEDANT\anaconda3\envs\tf_env\lib\site-packages\tensorboard\main.py", line 27, in <module>
    from tensorboard import default
  File "C:\Users\VEDANT\anaconda3\envs\tf_env\lib\site-packages\tensorboard\default.py", line 30, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

In [19]:
## Evalutate for the test datate
test_loss,test_mae = model.evaluate(X_test,y_test)
print(f'Test Loss: {test_loss}')
print(f'Test MAE: {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50164.5742 - mae: 50164.5742
Test Loss: 50164.57421875
Test MAE: 50164.57421875

In [20]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.